### ISSUE TITLE
Eastwood farm should probably have tools roundstart

### ISSUE THREAD

**Issue by Cartlord** [AtomBombf13/AtomBomb#193]
The Eastwood farm has absolutely no tools roundstart, and the lack of a NutriMax means you cannot get them. I believe that it should have a cultivator, spade, and bucket as well as a possible hatchet - just so that, say, a solo Barkeep can actually grow stuff for the kitchen.

**Comment by cornercube** [comment]
new map seems to solve this, theres a nutrimax in there
