### ISSUE TITLE
#129 broke mob's ability to fire multiple projectiles.

### ISSUE THREAD

**Issue by ErwinSnowden** [AtomBombf13/AtomBomb#288]
---- Testmerges: ----
N/A
---- Reproduction: ----
Test mobs, they fire their burst/extra_projectiles once and never again. This makes sentry bots useless.
---- Screenshots: ----
N/A
---- Additional context: ----
#129 broke this when it touched burst_size code. Pretty sure anyway, problems only started happening after it.

**Comment by BadAtThisGame302** [comment]
This is done.
