### ISSUE TITLE
LETPASSTHROW var broken

### ISSUE THREAD

**Issue by Pebblesthe2nd** [AtomBombf13/AtomBomb#295]
the variable pass_flags = LETPASSTHROW
does not work properly for barricades or anything really. It does nothing, only tables work.

To replicate: try throwing stuff over sandbags, barred doors etc.

Why it matters: You cant feed a prisoner by throwing fish in their face through the bars, nor flush out someone behind a sandbag by landing a molotov on their head

**Comment by xTrainx** [comment]
Unable to reproduce, probably fixed by #332, tho bars were made to be unthrowable on porpouse

**Comment by BadAtThisGame302** [comment]
This is fixed.
